<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-44CB39I" failures="1" tests="1" name="SelfRegistration" time="18.973" errors="0" timestamp="2023-07-02T20:27:29 IST">
  <testcase classname="QA_AccountManager_TestCases.SRbankingdetails_functional" name="Verifyalltypeofbankingdetails_error" time="9.576">
    <failure type="java.lang.AssertionError" message="expected [Company details added successfully] but found [Name of company has already been taken,Email of company has already been taken,Phone number of company has already been taken]">
      <![CDATA[java.lang.AssertionError: expected [Company details added successfully] but found [Name of company has already been taken,Email of company has already been taken,Phone number of company has already been taken]
at PageEvent.SRBankingDetailsFunctional.entercompanydetails(SRBankingDetailsFunctional.java:53)
at QA_AccountManager_TestCases.SRbankingdetails_functional.Verifyalltypeofbankingdetails_error(SRbankingdetails_functional.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Verifyalltypeofbankingdetails_error -->
</testsuite> <!-- SelfRegistration -->
