<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-02T20:27:10 IST" name="Suite" finished-at="2023-07-02T20:27:29 IST" duration-ms="18973">
    <groups>
    </groups>
    <test started-at="2023-07-02T20:27:10 IST" name="SelfRegistration" finished-at="2023-07-02T20:27:29 IST" duration-ms="18973">
      <class name="QA_AccountManager_TestCases.SRbankingdetails_functional">
        <test-method is-config="true" signature="beforetestmethod()[pri:0, instance:QA_AccountManager_TestCases.SRbankingdetails_functional@4961f6af]" started-at="2023-07-02T20:27:10 IST" name="beforetestmethod" finished-at="2023-07-02T20:27:10 IST" duration-ms="290" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetestmethod -->
        <test-method is-config="true" signature="beforeMethodMethod(java.lang.String,java.lang.reflect.Method)[pri:0, instance:QA_AccountManager_TestCases.SRbankingdetails_functional@4961f6af]" started-at="2023-07-02T20:27:10 IST" name="beforeMethodMethod" finished-at="2023-07-02T20:27:18 IST" duration-ms="8387" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void QA_AccountManager_TestCases.SRbankingdetails_functional.Verifyalltypeofbankingdetails_error() throws java.lang.InterruptedException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodMethod -->
        <test-method signature="Verifyalltypeofbankingdetails_error()[pri:0, instance:QA_AccountManager_TestCases.SRbankingdetails_functional@4961f6af]" started-at="2023-07-02T20:27:18 IST" name="Verifyalltypeofbankingdetails_error" finished-at="2023-07-02T20:27:28 IST" duration-ms="9576" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Company details added successfully] but found [Name of company has already been taken,Email of company has already been taken,Phone number of company has already been taken]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Company details added successfully] but found [Name of company has already been taken,Email of company has already been taken,Phone number of company has already been taken]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at PageEvent.SRBankingDetailsFunctional.entercompanydetails(SRBankingDetailsFunctional.java:53)
at QA_AccountManager_TestCases.SRbankingdetails_functional.Verifyalltypeofbankingdetails_error(SRbankingdetails_functional.java:18)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verifyalltypeofbankingdetails_error -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:QA_AccountManager_TestCases.SRbankingdetails_functional@4961f6af]" started-at="2023-07-02T20:27:28 IST" name="afterMethod" finished-at="2023-07-02T20:27:28 IST" duration-ms="335" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Verifyalltypeofbankingdetails_error status=FAILURE method=SRbankingdetails_functional.Verifyalltypeofbankingdetails_error()[pri:0, instance:QA_AccountManager_TestCases.SRbankingdetails_functional@4961f6af] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:QA_AccountManager_TestCases.SRbankingdetails_functional@4961f6af]" started-at="2023-07-02T20:27:28 IST" name="afterTest" finished-at="2023-07-02T20:27:29 IST" duration-ms="331" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- QA_AccountManager_TestCases.SRbankingdetails_functional -->
    </test> <!-- SelfRegistration -->
  </suite> <!-- Suite -->
</testng-results>
